### ISSUE TITLE
Setup Instructions Issue

### ISSUE THREAD

**Issue by xeryax** [BrobstonCreations/yet-another-smart-vent#17]
Awesome update, love the photos and everything-

The instructions no longer detail which pins need to be connected to what. e.g. how to connect the servo to the ESP board.

**Comment by xeryax** [comment]
im dumb- it is there

**Comment by TonyBrobston** [comment]
No biggie!

I was convinced there for a second that I had removed it.

Thanks for checking out the project. Let me know if you have any feedback!
