### ISSUE TITLE
Round vent designs?

### ISSUE THREAD

**Issue by trickv** [BrobstonCreations/yet-another-smart-vent#22]
Hi there,

Has anyone considered drawing up a round vent design? My house is all 6" round vents. I've tinkered with the idea of attaching a servo to one of [these](https://www.menards.com/main/p-1444429342306.htm) , but a 3D printed model would be easier to automate and for others to consume.

I have a printer and lots of ESP8266 boards, but barely a clue about how to draft 3D designs...but happy to team up with someone else who is interested.

**Comment by TonyBrobston** [comment]
> Hi there,

Hello 👋 
 
> Has anyone considered drawing up a round vent design? My house is all 6" round vents. I've tinkered with the idea of attaching a servo to one of [these](https://www.menards.com/main/p-1444429342306.htm) , but a 3D printed model would be easier to automate and for others to consume.

I haven't had this request yet. I'm sure something is doable. I'm happy to add it to the list in the readme, but I am not sure when I'll get to it as I have a lot of other things in the works at the moment.

> I have a printer and lots of ESP8266 boards, but barely a clue about how to draft 3D designs...but happy to team up with someone else who is interested.

I would definitely be up for collaborating in the future. 

I would also mention, this sort of situation is also a good opportunity to learn, if you're interested in getting into creating 3D designs. It really unlocks a lot of opportunity, especially if you have a 3d printer.

I've dabbled over the last 9-10 years and am now pretty proficient. I started with 2D and slowly got into 3D. I currently use Fusion 360, but have used MakerCAM, TinkerCAD, and SolidWorks a bit in the past. There are a lot of videos on YouTube where they walk through a design start to finish. If you watch enough of those, have the desire to create, and have a good amount of patience; you can make just about anything happen.

Initially I see two options:
1. Attach some sort of motor to a diffuser like you linked (or design something similar from scratch), then add a limit switch or two, depending on whether you can determine distance based on how many rotations the motor turns. However this approach is slightly different than what I am doing, but should be able to utilize one of ESPHome's "Cover" components (https://esphome.io/#cover-components).
2. Measure the duct opening and design a louver style vent. This would look similar to what I'm already doing, but the louvers would need designed around the vent's circular shape. It's kind of hard to describe and I'm certainly not accounting for other design constraints like how the louvers will interact with the circular shell and how that will impact the louver rotation, there's a bit of trial and error there that will need worked through. This design should be able to use the ESPHome configuartion that is project is using, as is. Though, it does feel like a literal circular peg in a round hole; so maybe there's a better design choice out there. Here's a super crude paint drawing:
![image](https://user-images.githubusercontent.com/4724577/194341236-6d2ae20d-a8a2-416b-ada7-8140f84a6bce.png)

**Comment by TonyBrobston** [comment]
I'm going to go ahead and close this. If you still have interest or other questions, feel free to reopen.
