### ISSUE TITLE
Request: 4x14 Vent Design

### ISSUE THREAD

**Issue by jametsitsi** [BrobstonCreations/yet-another-smart-vent#26]
I have a handful of registers that are 4x14. Is it possible to get a slightly longer model?

**Comment by TonyBrobston** [comment]
Yep. I'll add it to the list in the readme. Not quite sure when I'll get to it, but relatively soon.

**Comment by TonyBrobston** [comment]
I'm going to go ahead and close this issue. I've add 4x14 to the list and will get to it when I have time. I'll try to remember to write a comment here when it is done.

Let me know if you have any other questions.

**Comment by TonyBrobston** [comment]
@jametsitsi This now exists: https://www.printables.com/model/334635-yet-another-smart-vent-4x14

If you happen to print one, please upload a picture to Printables. If you run into issues, feel free to comment back here.

**Comment by jametsitsi** [comment]
@TonyBrobston Awesome, thanks for creating that! I'll get a picture posted when I print it out!
